// GENERATED by scripts/make-images.ts — do not edit by hand.
// Run `npm run images` after adding or replacing a photograph.
//
// Variants live under public/media/generated/, so their URLs are plain paths
// resolved against the deployment base. They must NOT go through
// import.meta.url: the build-time render happens in a separate SSR bundle, and
// that would bake a file:/// path from the build machine into the shipped HTML.
import type { ImageManifestEntry } from "../domain/types";

const base = import.meta.env.BASE_URL;

const url = (file: string): string => `${base}media/generated/${file}`;

export const imageManifest: ImageManifestEntry[] = [
  {
    "source": "hero-robertson-road.jpg",
    "width": 1920,
    "height": 1280,
    "aspectRatio": 1.5,
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "url": url("hero-robertson-road-640.avif"),
        "bytes": 2612
      },
      {
        "format": "webp",
        "width": 640,
        "url": url("hero-robertson-road-640.webp"),
        "bytes": 3360
      },
      {
        "format": "jpeg",
        "width": 640,
        "url": url("hero-robertson-road-640.jpg"),
        "bytes": 4928
      },
      {
        "format": "avif",
        "width": 1280,
        "url": url("hero-robertson-road-1280.avif"),
        "bytes": 5396
      },
      {
        "format": "webp",
        "width": 1280,
        "url": url("hero-robertson-road-1280.webp"),
        "bytes": 8904
      },
      {
        "format": "jpeg",
        "width": 1280,
        "url": url("hero-robertson-road-1280.jpg"),
        "bytes": 13351
      },
      {
        "format": "avif",
        "width": 1920,
        "url": url("hero-robertson-road-1920.avif"),
        "bytes": 8589
      },
      {
        "format": "webp",
        "width": 1920,
        "url": url("hero-robertson-road-1920.webp"),
        "bytes": 16002
      },
      {
        "format": "jpeg",
        "width": 1920,
        "url": url("hero-robertson-road-1920.jpg"),
        "bytes": 25290
      }
    ]
  },
  {
    "source": "stop-1-st-paul.jpg",
    "width": 1920,
    "height": 1280,
    "aspectRatio": 1.5,
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "url": url("stop-1-st-paul-640.avif"),
        "bytes": 2471
      },
      {
        "format": "webp",
        "width": 640,
        "url": url("stop-1-st-paul-640.webp"),
        "bytes": 3202
      },
      {
        "format": "jpeg",
        "width": 640,
        "url": url("stop-1-st-paul-640.jpg"),
        "bytes": 4791
      },
      {
        "format": "avif",
        "width": 1280,
        "url": url("stop-1-st-paul-1280.avif"),
        "bytes": 5037
      },
      {
        "format": "webp",
        "width": 1280,
        "url": url("stop-1-st-paul-1280.webp"),
        "bytes": 8398
      },
      {
        "format": "jpeg",
        "width": 1280,
        "url": url("stop-1-st-paul-1280.jpg"),
        "bytes": 12919
      },
      {
        "format": "avif",
        "width": 1920,
        "url": url("stop-1-st-paul-1920.avif"),
        "bytes": 7844
      },
      {
        "format": "webp",
        "width": 1920,
        "url": url("stop-1-st-paul-1920.webp"),
        "bytes": 15074
      },
      {
        "format": "jpeg",
        "width": 1920,
        "url": url("stop-1-st-paul-1920.jpg"),
        "bytes": 24377
      }
    ]
  },
  {
    "source": "stop-2-st-john.jpg",
    "width": 1920,
    "height": 1280,
    "aspectRatio": 1.5,
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "url": url("stop-2-st-john-640.avif"),
        "bytes": 2447
      },
      {
        "format": "webp",
        "width": 640,
        "url": url("stop-2-st-john-640.webp"),
        "bytes": 3186
      },
      {
        "format": "jpeg",
        "width": 640,
        "url": url("stop-2-st-john-640.jpg"),
        "bytes": 4785
      },
      {
        "format": "avif",
        "width": 1280,
        "url": url("stop-2-st-john-1280.avif"),
        "bytes": 5034
      },
      {
        "format": "webp",
        "width": 1280,
        "url": url("stop-2-st-john-1280.webp"),
        "bytes": 8382
      },
      {
        "format": "jpeg",
        "width": 1280,
        "url": url("stop-2-st-john-1280.jpg"),
        "bytes": 12909
      },
      {
        "format": "avif",
        "width": 1920,
        "url": url("stop-2-st-john-1920.avif"),
        "bytes": 7728
      },
      {
        "format": "webp",
        "width": 1920,
        "url": url("stop-2-st-john-1920.webp"),
        "bytes": 15140
      },
      {
        "format": "jpeg",
        "width": 1920,
        "url": url("stop-2-st-john-1920.jpg"),
        "bytes": 24300
      }
    ]
  },
  {
    "source": "stop-3-stinson-avenue.jpg",
    "width": 1920,
    "height": 1280,
    "aspectRatio": 1.5,
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "url": url("stop-3-stinson-avenue-640.avif"),
        "bytes": 2479
      },
      {
        "format": "webp",
        "width": 640,
        "url": url("stop-3-stinson-avenue-640.webp"),
        "bytes": 3220
      },
      {
        "format": "jpeg",
        "width": 640,
        "url": url("stop-3-stinson-avenue-640.jpg"),
        "bytes": 4769
      },
      {
        "format": "avif",
        "width": 1280,
        "url": url("stop-3-stinson-avenue-1280.avif"),
        "bytes": 5066
      },
      {
        "format": "webp",
        "width": 1280,
        "url": url("stop-3-stinson-avenue-1280.webp"),
        "bytes": 8506
      },
      {
        "format": "jpeg",
        "width": 1280,
        "url": url("stop-3-stinson-avenue-1280.jpg"),
        "bytes": 12939
      },
      {
        "format": "avif",
        "width": 1920,
        "url": url("stop-3-stinson-avenue-1920.avif"),
        "bytes": 7840
      },
      {
        "format": "webp",
        "width": 1920,
        "url": url("stop-3-stinson-avenue-1920.webp"),
        "bytes": 15436
      },
      {
        "format": "jpeg",
        "width": 1920,
        "url": url("stop-3-stinson-avenue-1920.jpg"),
        "bytes": 24621
      }
    ]
  },
  {
    "source": "stop-4-our-lady-of-peace.jpg",
    "width": 1920,
    "height": 1280,
    "aspectRatio": 1.5,
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "url": url("stop-4-our-lady-of-peace-640.avif"),
        "bytes": 2440
      },
      {
        "format": "webp",
        "width": 640,
        "url": url("stop-4-our-lady-of-peace-640.webp"),
        "bytes": 3218
      },
      {
        "format": "jpeg",
        "width": 640,
        "url": url("stop-4-our-lady-of-peace-640.jpg"),
        "bytes": 4760
      },
      {
        "format": "avif",
        "width": 1280,
        "url": url("stop-4-our-lady-of-peace-1280.avif"),
        "bytes": 5004
      },
      {
        "format": "webp",
        "width": 1280,
        "url": url("stop-4-our-lady-of-peace-1280.webp"),
        "bytes": 8462
      },
      {
        "format": "jpeg",
        "width": 1280,
        "url": url("stop-4-our-lady-of-peace-1280.jpg"),
        "bytes": 12903
      },
      {
        "format": "avif",
        "width": 1920,
        "url": url("stop-4-our-lady-of-peace-1920.avif"),
        "bytes": 7599
      },
      {
        "format": "webp",
        "width": 1920,
        "url": url("stop-4-our-lady-of-peace-1920.webp"),
        "bytes": 14948
      },
      {
        "format": "jpeg",
        "width": 1920,
        "url": url("stop-4-our-lady-of-peace-1920.jpg"),
        "bytes": 24166
      }
    ]
  },
  {
    "source": "stop-5-mcdonalds.jpg",
    "width": 1920,
    "height": 1280,
    "aspectRatio": 1.5,
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "url": url("stop-5-mcdonalds-640.avif"),
        "bytes": 2563
      },
      {
        "format": "webp",
        "width": 640,
        "url": url("stop-5-mcdonalds-640.webp"),
        "bytes": 3366
      },
      {
        "format": "jpeg",
        "width": 640,
        "url": url("stop-5-mcdonalds-640.jpg"),
        "bytes": 4870
      },
      {
        "format": "avif",
        "width": 1280,
        "url": url("stop-5-mcdonalds-1280.avif"),
        "bytes": 5301
      },
      {
        "format": "webp",
        "width": 1280,
        "url": url("stop-5-mcdonalds-1280.webp"),
        "bytes": 8746
      },
      {
        "format": "jpeg",
        "width": 1280,
        "url": url("stop-5-mcdonalds-1280.jpg"),
        "bytes": 13329
      },
      {
        "format": "avif",
        "width": 1920,
        "url": url("stop-5-mcdonalds-1920.avif"),
        "bytes": 8204
      },
      {
        "format": "webp",
        "width": 1920,
        "url": url("stop-5-mcdonalds-1920.webp"),
        "bytes": 15756
      },
      {
        "format": "jpeg",
        "width": 1920,
        "url": url("stop-5-mcdonalds-1920.jpg"),
        "bytes": 24930
      }
    ]
  },
  {
    "source": "stop-6-canadian-tire.jpg",
    "width": 1920,
    "height": 1280,
    "aspectRatio": 1.5,
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "url": url("stop-6-canadian-tire-640.avif"),
        "bytes": 2176
      },
      {
        "format": "webp",
        "width": 640,
        "url": url("stop-6-canadian-tire-640.webp"),
        "bytes": 2896
      },
      {
        "format": "jpeg",
        "width": 640,
        "url": url("stop-6-canadian-tire-640.jpg"),
        "bytes": 4334
      },
      {
        "format": "avif",
        "width": 1280,
        "url": url("stop-6-canadian-tire-1280.avif"),
        "bytes": 4433
      },
      {
        "format": "webp",
        "width": 1280,
        "url": url("stop-6-canadian-tire-1280.webp"),
        "bytes": 7728
      },
      {
        "format": "jpeg",
        "width": 1280,
        "url": url("stop-6-canadian-tire-1280.jpg"),
        "bytes": 11932
      },
      {
        "format": "avif",
        "width": 1920,
        "url": url("stop-6-canadian-tire-1920.avif"),
        "bytes": 6902
      },
      {
        "format": "webp",
        "width": 1920,
        "url": url("stop-6-canadian-tire-1920.webp"),
        "bytes": 14008
      },
      {
        "format": "jpeg",
        "width": 1920,
        "url": url("stop-6-canadian-tire-1920.jpg"),
        "bytes": 22513
      }
    ]
  },
  {
    "source": "stop-7-britannia-beach.jpg",
    "width": 1920,
    "height": 1280,
    "aspectRatio": 1.5,
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "url": url("stop-7-britannia-beach-640.avif"),
        "bytes": 2535
      },
      {
        "format": "webp",
        "width": 640,
        "url": url("stop-7-britannia-beach-640.webp"),
        "bytes": 3340
      },
      {
        "format": "jpeg",
        "width": 640,
        "url": url("stop-7-britannia-beach-640.jpg"),
        "bytes": 4838
      },
      {
        "format": "avif",
        "width": 1280,
        "url": url("stop-7-britannia-beach-1280.avif"),
        "bytes": 5262
      },
      {
        "format": "webp",
        "width": 1280,
        "url": url("stop-7-britannia-beach-1280.webp"),
        "bytes": 8742
      },
      {
        "format": "jpeg",
        "width": 1280,
        "url": url("stop-7-britannia-beach-1280.jpg"),
        "bytes": 13126
      },
      {
        "format": "avif",
        "width": 1920,
        "url": url("stop-7-britannia-beach-1920.avif"),
        "bytes": 8282
      },
      {
        "format": "webp",
        "width": 1920,
        "url": url("stop-7-britannia-beach-1920.webp"),
        "bytes": 15868
      },
      {
        "format": "jpeg",
        "width": 1920,
        "url": url("stop-7-britannia-beach-1920.jpg"),
        "bytes": 24900
      }
    ]
  }
];

/** Look up an entry by the source path written in the authored content. */
export function lookupImage(source: string): ImageManifestEntry | undefined {
  return imageManifest.find((entry) => entry.source === source);
}
